export { OnBoard } from './onboard/OnBoard';
export { HomePage } from './home';
export { ProfilePage } from './profile';
export { UserProfilePage } from './userProfile';
export { EditProfilePage } from './editProfile';
export { FriendsPage } from './friends';
export { InviteLanding } from './invite';
export { LandingPage } from './landing';
export { ThankYou } from './thankYou';
