# Generated by Django 6.0.4 on 2026-05-09 23:41

import django.db.models.deletion
import event.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("wish", "Wish"), ("plan", "Plan")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to=event.models.upload_cover_image
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("external_link", models.URLField(blank=True, null=True)),
                ("event_date", models.DateField(blank=True, null=True)),
                ("event_time", models.TimeField(blank=True, null=True)),
                (
                    "timeframe_text",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("min_participants", models.PositiveIntegerField(default=1)),
                ("max_participants", models.PositiveIntegerField()),
                ("participants_count", models.PositiveIntegerField(default=0)),
                ("interested_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="event.category",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("interested", "Interested"),
                            ("joined", "Joined"),
                            ("left", "Left"),
                        ],
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="event.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["creator"], name="event_event_creator_292d92_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_type"], name="event_event_event_t_df5a4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="event_event_status_179731_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["event_date"], name="event_event_event_d_89e7d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["created_at"], name="event_event_created_105efb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["event"], name="event_event_event_i_cd34af_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["user"], name="event_event_user_id_7a0b8f_idx"),
        ),
        migrations.AddIndex(
            model_name="eventparticipant",
            index=models.Index(fields=["status"], name="event_event_status_051de7_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventparticipant",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="unique_event_user"
            ),
        ),
    ]
