# Generated by Django 6.0.4 on 2026-05-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
