# Generated by Django 6.0.4 on 2026-05-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_description_alter_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="max_participants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
