# Generated by Django 6.0.4 on 2026-05-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_alter_event_max_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                default="No details added by the host.", max_length=200
            ),
        ),
    ]
