# Generated by Django 6.0.4 on 2026-05-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("completed", "Completed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
