# Generated by Django 6.0.3 on 2026-05-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_visibility",
            field=models.CharField(
                choices=[("friends-only", "FRIENDS-ONLY"), ("f-o-f", "F-O-F")],
                default="friends-only",
                max_length=15,
            ),
        ),
    ]
