# Generated by Django 6.0.4 on 2026-06-17 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_event_event_visibility"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventparticipant",
            new_name="event_parti_event_i_1e5dfd_idx",
            old_name="event_event_event_i_cd34af_idx",
        ),
        migrations.RenameIndex(
            model_name="eventparticipant",
            new_name="event_parti_user_id_91482b_idx",
            old_name="event_event_user_id_7a0b8f_idx",
        ),
        migrations.RenameIndex(
            model_name="eventparticipant",
            new_name="event_parti_status_944ac7_idx",
            old_name="event_event_status_051de7_idx",
        ),
        migrations.AlterField(
            model_name="event",
            name="event_visibility",
            field=models.CharField(
                choices=[("friends-only", "FRIENDS-ONLY"), ("f-o-f", "F-O-F")],
                default="f-o-f",
                max_length=15,
            ),
        ),
        migrations.AlterModelTable(
            name="eventparticipant",
            table="event_participant",
        ),
    ]
