# Generated by Django 6.0.4 on 2026-06-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "event",
            "0007_rename_event_event_event_i_cd34af_idx_event_parti_event_i_1e5dfd_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="eventparticipant",
            new_name="event_event_event_i_cd34af_idx",
            old_name="event_parti_event_i_1e5dfd_idx",
        ),
        migrations.RenameIndex(
            model_name="eventparticipant",
            new_name="event_event_user_id_7a0b8f_idx",
            old_name="event_parti_user_id_91482b_idx",
        ),
        migrations.RenameIndex(
            model_name="eventparticipant",
            new_name="event_event_status_051de7_idx",
            old_name="event_parti_status_944ac7_idx",
        ),
        migrations.AlterModelTable(
            name="eventparticipant",
            table=None,
        ),
    ]
