# Generated by Django 6.0.3 on 2026-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "event",
            "0008_rename_event_parti_event_i_1e5dfd_idx_event_event_event_i_cd34af_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_visibility",
            field=models.CharField(
                choices=[("f-o-f", "F-O-F"), ("friends-only", "FRIENDS-ONLY")],
                default="f-o-f",
                max_length=15,
            ),
        ),
    ]
