# Generated by Django 6.0.3 on 2026-07-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_alter_event_event_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="share_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="share_revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="share_token",
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
