# Generated by Django 6.0.3 on 2026-07-28 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_event_share_expires_at_event_share_revoked_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="share_expires_at",
        ),
        migrations.RemoveField(
            model_name="event",
            name="share_revoked_at",
        ),
    ]
