# Generated by Django 6.0.3 on 2026-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0011_remove_event_share_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_place_id",
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
