# Generated by Django 6.0.4 on 2026-05-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("friend_request", "Friend Request"),
                    ("friend_request_accepted", "Friend Request Accepted"),
                    ("joined_event", "Joined Event"),
                    ("interested_event", "Interested Event"),
                    ("event_planned", "Event Planned"),
                    ("event_start_reminder", "Event Start Reminder"),
                    ("event_updated", "Event Updated"),
                    ("event_cancelled", "Event Cancelled"),
                ],
                max_length=64,
            ),
        ),
    ]
