import { vi } from 'vitest';

export const backendMocks = {
  auth: {
    emailStart: vi.fn(),
    verifyCode: vi.fn(),
    google: vi.fn(),
    getTokens: vi.fn(),
    setPassword: vi.fn(),
    resetPassword: vi.fn(),
    setNewPassword: vi.fn(),
    logout: vi.fn(),
  },
  user: {
    me: vi.fn(),
    onboarding: vi.fn(),
    updateProfile: vi.fn(),
    changePassword: vi.fn(),
    avatar: vi.fn(),
    feedTourSeen: vi.fn(),
    checkUsername: vi.fn(),
    invite: vi.fn(),
    inviteUse: vi.fn(),
    profileList: vi.fn(),
    events: vi.fn(),
    friendshipFriends: vi.fn(),
    friendshipIncoming: vi.fn(),
    friendshipList: vi.fn(),
    friendshipAccept: vi.fn(),
    friendshipDecline: vi.fn(),
    friendshipRemove: vi.fn(),
    friendshipSend: vi.fn(),
  },
  event: {
    list: vi.fn(),
    get: vi.fn(),
    remove: vi.fn(),
    categories: vi.fn(),
    action: vi.fn(),
    participants: vi.fn(),
    createShareLink: vi.fn(),
    create: vi.fn(),
    update: vi.fn(),
    convert: vi.fn(),
  },
  notifications: {
    list: vi.fn(),
    unreadCount: vi.fn(),
    readAll: vi.fn(),
  },
};
