# Generated by Django 6.0.4 on 2026-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_emailverification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailverification",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
