# Generated by Django 6.0.4 on 2026-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_emailverification_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
