# Generated by Django 6.0.4 on 2026-04-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
