# Generated by Django 6.0.4 on 2026-04-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_profile_is_onboarded"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
