# Generated by Django 6.0.4 on 2026-05-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_emailverification_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="purpose",
            field=models.CharField(default="registration", max_length=20),
        ),
    ]
