# Generated by Django 6.0.4 on 2026-05-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_friendinvite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=20,
                null=True,
            ),
        ),
    ]
