# Generated by Django 6.0.4 on 2026-05-16 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_profile_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendinvite",
            name="is_used",
        ),
    ]
