# Generated by Django 6.0.4 on 2026-06-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0012_profile_is_private"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="emailverification",
            table="email_verification",
        ),
        migrations.AlterModelTable(
            name="friendinvite",
            table="friend_invite",
        ),
        migrations.AlterModelTable(
            name="socialaccount",
            table="social_account",
        ),
    ]
