# Generated by Django 6.0.4 on 2026-06-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0013_alter_emailverification_table_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="emailverification",
            table=None,
        ),
        migrations.AlterModelTable(
            name="friendinvite",
            table=None,
        ),
        migrations.AlterModelTable(
            name="socialaccount",
            table=None,
        ),
    ]
