# Generated by Django 6.0.3 on 2026-07-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_emailverification_table_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendship",
            name="accepted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="friendship",
            name="followup_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
