# Generated by Django 6.0.3 on 2026-08-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_friendship_accepted_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="has_seen_feed_tour",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
