# Generated by Django 6.0.3 on 2026-09-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0016_profile_has_seen_feed_tour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="has_seen_feed_tour",
            field=models.BooleanField(default=False),
        ),
    ]
