import type { TourStep } from './types';

export const buildFeedTourSteps = (name?: string | null): TourStep[] => [
  {
    id: 'welcome',
    title: name ? `Welcome, ${name}` : 'Welcome to WishWe',
    body: 'Every plan and wish your friends share lands right here. Here’s a quick look around — it takes under a minute.',
    primaryLabel: 'Show me around',
    secondaryLabel: 'Skip for now',
  },
  {
    id: 'feed-events',
    anchor: 'feed-card',
    title: 'Two kinds of ideas',
    body: 'Every card is one idea. A plan has a date and a set number of spots you can join; a wish is still loose, so you mark yourself interested instead.',
    placement: 'bottom',
    padding: 6,
    radius: 20,
  },
  {
    id: 'feed-empty',
    anchor: 'feed-empty',
    title: 'Quiet in here — for now',
    body: 'Plans and wishes from your friends will show up right here. Add a few friends, or start the first idea yourself.',
    placement: 'bottom',
    padding: 16,
    radius: 20,
  },
  {
    id: 'toolbar',
    anchor: 'feed-toolbar',
    title: 'Filter and sort',
    body: 'Switch between plans and wishes, narrow the feed down to direct friends, or reorder it — soonest first, recently added, or by social heat.',
    placement: 'bottom',
    padding: 12,
    radius: 14,
  },
  {
    id: 'search',
    anchor: 'feed-search',
    title: 'Find something specific',
    body: 'Search your feed by title. It switches on as soon as there are events to look through.',
    placement: 'bottom',
    padding: 6,
  },
  {
    id: 'create',
    anchor: 'create-event',
    title: 'Start your own',
    body: 'A plan when you already know the date, a wish when you don’t. Either way your friends see it right away.',
    placement: 'bottom',
    padding: 6,
  },
  {
    id: 'notifications',
    anchor: 'notifications',
    title: 'Nothing slips past',
    body: 'Friend requests, people joining your plans, and a nudge before an event starts all arrive here.',
    placement: 'bottom',
    padding: 4,
  },
  {
    id: 'friends',
    anchor: 'nav-friends',
    title: 'Better with friends',
    body: 'Your feed is built from your friends’ ideas. Find people you know here, or grab an invite link for the ones who aren’t on WishWe yet.',
    placement: 'right',
    padding: 4,
  },
  {
    id: 'profile',
    anchor: 'nav-profile',
    title: 'Your corner',
    body: 'Everything you create lives on your profile — upcoming plans, open wishes, and the ones you’ve already archived.',
    placement: 'right',
    padding: 4,
  },
  {
    id: 'done',
    title: 'That’s the tour',
    body: 'Add a couple of friends, drop in your first idea, and your feed starts filling itself.',
    primaryLabel: 'Got it',
  },
];
